name: Django Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_services:
    strategy:
      matrix:
        servicios: 
          - 'services/web_frontend'
          - 'services/service_usuarios'
          - 'services/service_lugares'
          - 'services/service_interacciones'
          - 'services/service_eventos'
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install and Test ${{ matrix.servicios }}
        run: |
          cd ${{ matrix.servicios }}

          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python manage.py test
