name: Django Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_services:
    strategy:
      matrix:
        servicios: 
          - 'services/web_frontend'
          - 'services/service_usuarios'
          - 'services/service_lugares'
          - 'services/service_interacciones'
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install Dependencies for ${{ matrix.servicios }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ matrix.servicios }}

      - name: Run Tests for ${{ matrix.servicios }}
        run: |
          echo "Ejecutando tests en $(pwd)"
          python manage.py test
        working-directory: ${{ matrix.servicios }}
